import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./../globals.css";
import FooterSection from "@/app/components/FooterSection";

const manrope = Manrope({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${manrope.className} antialiased`}>
        <body
            className={``}
        >
            {children}
            <FooterSection/>
        </body>
        </html>
    );
}
